version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    image: lesflqq/back-tech-project
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-csvpkb3qf0us73fv8lhg-a.oregon-postgres.render.com:5432/back_tech_db_mmdm
      SPRING_DATASOURCE_USERNAME: ussser
      SPRING_DATASOURCE_PASSWORD: 1XtU6j3XRO8yzLUIfz89QQjZd6b4qcWD
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: backend-technologies
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: back_tech_db_mmdm
      POSTGRES_USER: ussser
      POSTGRES_PASSWORD: 1XtU6j3XRO8yzLUIfz89QQjZd6b4qcWD
    ports:
      - "5432:5432"
